set_property SRC_FILE_INFO {cfile:n:/ECE540/Project1/project_simplebot_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc rfile:../../../../../project_simplebot_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc id:1 order:EARLY scoped_inst:clk_wiz_0} [current_design]
set_property SRC_FILE_INFO {cfile:N:/ECE540/Project1/project_simplebot_1.srcs/constrs_1/imports/constraints/mfp_nexys4_ddr.xdc rfile:../../../../../project_simplebot_1.srcs/constrs_1/imports/constraints/mfp_nexys4_ddr.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name CLK100MHZ [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_wiz_0/clk_out1 -source [get_ports CLK100MHZ] -edges {1 2 3} -edge_shift {0.000 5.000 10.000} [get_pins clk_wiz_0/clk_out1]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports CLK100MHZ]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells clk_wiz_0]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK100MHZ]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets tck_in]
set_property src_info {type:XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {JB[7]}]
set_property src_info {type:XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {JB[8]}]
set_property src_info {type:XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 -name clk_virt
set_property src_info {type:XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 -name tck
set_property src_info {type:XDC file:2 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -physically_exclusive -group clk_virt
set_property src_info {type:XDC file:2 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -physically_exclusive -group tck
set_property src_info {type:XDC file:2 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -min -add_delay 0.000 [get_ports {SW[*]}]
set_property src_info {type:XDC file:2 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -max -add_delay 20.000 [get_ports {SW[*]}]
set_property src_info {type:XDC file:2 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -min -add_delay 0.000 [get_ports BTNC]
set_property src_info {type:XDC file:2 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -max -add_delay 20.000 [get_ports BTNC]
set_property src_info {type:XDC file:2 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -min -add_delay 0.000 [get_ports CPU_RESETN]
set_property src_info {type:XDC file:2 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -max -add_delay 20.000 [get_ports CPU_RESETN]
set_property src_info {type:XDC file:2 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -min -add_delay 0.000 [get_ports BTND]
set_property src_info {type:XDC file:2 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -max -add_delay 20.000 [get_ports BTND]
set_property src_info {type:XDC file:2 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -min -add_delay 0.000 [get_ports BTNL]
set_property src_info {type:XDC file:2 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -max -add_delay 20.000 [get_ports BTNL]
set_property src_info {type:XDC file:2 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -min -add_delay 0.000 [get_ports BTNR]
set_property src_info {type:XDC file:2 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -max -add_delay 20.000 [get_ports BTNR]
set_property src_info {type:XDC file:2 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -min -add_delay 0.000 [get_ports BTNU]
set_property src_info {type:XDC file:2 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -max -add_delay 20.000 [get_ports BTNU]
set_property src_info {type:XDC file:2 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -min -add_delay 0.000 [get_ports {JB[1]}]
set_property src_info {type:XDC file:2 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -max -add_delay 20.000 [get_ports {JB[1]}]
set_property src_info {type:XDC file:2 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -min -add_delay 0.000 [get_ports {JB[2]}]
set_property src_info {type:XDC file:2 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -max -add_delay 20.000 [get_ports {JB[2]}]
set_property src_info {type:XDC file:2 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -min -add_delay 0.000 [get_ports {JB[4]}]
set_property src_info {type:XDC file:2 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clk_virt -max -add_delay 20.000 [get_ports {JB[4]}]
set_property src_info {type:XDC file:2 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -min -add_delay 0.000 [get_ports {LED[*]}]
set_property src_info {type:XDC file:2 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -max -add_delay 20.000 [get_ports {LED[*]}]
set_property src_info {type:XDC file:2 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -min -add_delay 0.000 [get_ports {JB[3]}]
set_property src_info {type:XDC file:2 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -max -add_delay 20.000 [get_ports {JB[3]}]
set_property src_info {type:XDC file:2 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -min -add_delay 0.000 [get_ports {AN[*]}]
set_property src_info {type:XDC file:2 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -max -add_delay 20.000 [get_ports {AN[*]}]
set_property src_info {type:XDC file:2 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -min -add_delay 0.000 [get_ports CA]
set_property src_info {type:XDC file:2 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -max -add_delay 20.000 [get_ports CA]
set_property src_info {type:XDC file:2 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -min -add_delay 0.000 [get_ports CB]
set_property src_info {type:XDC file:2 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -max -add_delay 20.000 [get_ports CB]
set_property src_info {type:XDC file:2 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -min -add_delay 0.000 [get_ports CC]
set_property src_info {type:XDC file:2 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -max -add_delay 20.000 [get_ports CC]
set_property src_info {type:XDC file:2 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -min -add_delay 0.000 [get_ports CD]
set_property src_info {type:XDC file:2 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -max -add_delay 20.000 [get_ports CD]
set_property src_info {type:XDC file:2 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -min -add_delay 0.000 [get_ports CE]
set_property src_info {type:XDC file:2 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -max -add_delay 20.000 [get_ports CE]
set_property src_info {type:XDC file:2 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -min -add_delay 0.000 [get_ports CF]
set_property src_info {type:XDC file:2 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -max -add_delay 20.000 [get_ports CF]
set_property src_info {type:XDC file:2 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -min -add_delay 0.000 [get_ports CG]
set_property src_info {type:XDC file:2 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -max -add_delay 20.000 [get_ports CG]
set_property src_info {type:XDC file:2 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -min -add_delay 0.000 [get_ports DP]
set_property src_info {type:XDC file:2 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clk_virt -max -add_delay 20.000 [get_ports DP]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells clk_wiz_0]
